### ISSUE TITLE
ordered_by_ancestry bugs

### ISSUE THREAD

**Issue by Fryguy** [stefankroes/ancestry#217] opened 2014-12-19 17:30 UTC
In my application, calling .descendants is not returning the records ordered by ancestry as I would have expected.

I've noticed a few issues with `ordered_by_ancestry`, and each one is complicating the solution of the other, so I'm looking for some help before issuing a PR.

First, I noticed that the `ordered_by_ancestry` method is not working as expected for `.descendants` (nor `.subtree`).  The line in question is [here](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/lib/ancestry/instance_methods.rb#L243).  Notice the `ordered_by_ancestry` before `scope_depth`.  This _should_ work, but the `scope_depth` call after kills all scopes before it by restarting the scoping from `ancestor_base_class` [here](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/lib/ancestry/class_methods.rb#L10).

For our code, the SQL generated by that code is

``` sql
  Relationship Load (1.2ms)  SELECT "relationships".* FROM "relationships" WHERE (("relationships"."ancestry" ILIKE '134/135/136/202/803/%' OR "relationships"."ancestry" = '134/135/136/202/803'))
```

Notice the lack of `ORDER BY` clause. If I put the `ordered_by_ancestry` after the `scope_depth`, the SQL becomes:

``` sql
  Relationship Load (1.7ms)  SELECT "relationships".* FROM "relationships" WHERE (("relationships"."ancestry" ILIKE '134/135/136/202/803/%' OR "relationships"."ancestry" = '134/135/136/202/803')) ORDER BY (case when relationships.ancestry is null then 0 else 1 end), relationships.ancestry
```

Also note that the [ancestors method](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/lib/ancestry/instance_methods.rb#L116) and the [path method](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/lib/ancestry/instance_methods.rb#L137) do the "right" thing already, but the [descendants method](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/lib/ancestry/instance_methods.rb#L243) and the [subtree method](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/lib/ancestry/instance_methods.rb#L258) do the "wrong" thing.

So, if I switch those two statements the tests fail [here](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/test/concerns/scopes_test.rb#L17) and [here](https://github.com/stefankroes/ancestry/blob/2d80781c4f8f95183e446198d0128314bff0ca88/test/concerns/tree_navigration_test.rb#L35).  The reason, I think is because now the ordering of the nodes has changed, and I'm not 100% sure how to fix.

Even so, the nodes are _still_ in the wrong order, which leads to the next problem with `ordered_by_ancestry`, and that is that ultimately it sorts by the `ancestry` column.  The problem there is that it does a string sort instead of a numerical sort, thus putting id "10" before "2".  I'm not sure where to even begin with this.  Any thoughts?  Should we just throw away `ordered_by_ancestry`, since it doesn't work anyway?  Should we maybe leverage `sort_by_ancestry` method instead (i.e. sort in Ruby)?

**Comment by vanderhoorn** [comment] 2015-01-11 21:18
I understand your problem.

The ancestry gem is for storing ActiveRecord objects in a treelike structure. Because it stores the parents of an object in one column, querying (sub)trees is very easy, but sorting is not. I recommend adding a ```position``` column for keeping track of the order of branches.

**Comment by stefankroes** [comment] 2015-01-12 05:56
Exactly, Ancestry was designed to work well with gems such as act_as_list (but there are many others) that handle ordering. Ordering is out of scope regarding Ancestry.

**Comment by Fryguy** [comment] 2015-05-15 21:02
If that's the case, then should we just kill the `ordered_by_ancestry` method entirely?  I'm not sure what it is buying us.

**Comment by stefankroes** [comment] 2015-05-16 09:12
It's orders by tree structure so that parents come before children. It's the basis for arrangement.

**Comment by kbrock** [comment] 2018-11-03 00:34
Relationships are hard. especially when referring to ancestors.

The method has changed quite a bit. Please reopen if you have any suggestions that will make your relationships easier.

--Keenan 😉 :trollface:

**Closed by kbrock** 2018-11-03 00:34 UTC
